apiVersion: v1
kind: ConfigMap
metadata:
  name: devethops-config
  labels:
    app: devethops-framework
data:
  # Database configuration
  postgres_host: "postgres-service"
  postgres_port: "5432"
  postgres_db: "devethops"
  postgres_user: "devethops"
  
  # Redis configuration
  redis_host: "redis-service"
  redis_port: "6379"
  
  # MongoDB configuration
  mongodb_host: "mongodb-service"
  mongodb_port: "27017"
  
  # Application configuration
  app_environment: "kubernetes"
  log_level: "INFO"
  max_workers: "4"
  
  # Fairness thresholds
  fairness_demographic_parity_threshold: "0.1"
  fairness_disparate_impact_threshold: "0.8"
  fairness_equalized_odds_threshold: "0.1"
  
  # Performance thresholds
  performance_accuracy_threshold: "0.8"
  performance_precision_threshold: "0.75"
  performance_recall_threshold: "0.75"
  performance_f1_threshold: "0.75"
  
  # Explainability configuration
  explainability_enable_shap: "true"
  explainability_enable_lime: "true"
  explainability_sample_size: "1000"
  
  # Monitoring configuration
  monitoring_enable_prometheus: "true"
  monitoring_metrics_port: "8080"
  monitoring_health_check_interval: "30"
  
  # Pipeline configuration
  pipeline_config.yaml: |
    pipeline:
      name: "DevEthOps Ethical AI Pipeline"
      version: "1.0.0"
      stages:
        - build
        - test
        - deploy
        - monitor
      
      build:
        enable_bias_detection: true
        enable_data_validation: true
        bias_mitigation_strategy: "reweighting"
      
      test:
        fairness_tests: true
        explainability_tests: true
        performance_tests: true
        integration_tests: true
      
      deploy:
        containerization: true
        kubernetes_deployment: true
        monitoring_setup: true
        rollback_enabled: true
      
      monitor:
        drift_detection: true
        fairness_monitoring: true
        performance_monitoring: true
        alert_thresholds:
          fairness_drop: 0.05
          performance_drop: 0.1
  
  fairness_thresholds.yaml: |
    fairness_metrics:
      demographic_parity:
        threshold: 0.1
        weight: 0.3
      disparate_impact:
        threshold: 0.8
        weight: 0.3
      equalized_odds:
        threshold: 0.1
        weight: 0.2
      individual_fairness:
        threshold: 0.05
        weight: 0.2
    
    protected_attributes:
      - "gender"
      - "race"
      - "age_group"
      - "income_level"
    
    fairness_evaluation:
      enable_intersectional: true
      sample_size: 10000
      confidence_level: 0.95
  
  model_config.yaml: |
    models:
      llm:
        type: "transformer"
        architecture: "bert-base-uncased"
        max_length: 512
        batch_size: 16
        learning_rate: 2e-5
        epochs: 3
        
      fairness_classifier:
        type: "ensemble"
        base_models: ["random_forest", "gradient_boosting"]
        fairness_constraints: true
        
    training:
      validation_split: 0.2
      early_stopping: true
      fairness_regularization: 0.1
      
    evaluation:
      cross_validation_folds: 5
      fairness_evaluation: true
      explainability_analysis: true

---
apiVersion: v1
kind: Secret
metadata:
  name: devethops-secrets
  labels:
    app: devethops-framework
type: Opaque
data:
  # Base64 encoded secrets
  postgres_password: ZGV2ZXRob3BzMTIz  # devethops123
  redis_password: ""
  mongodb_password: ZGV2ZXRob3BzMTIz  # devethops123
  jwt_secret: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here
  api_key: eW91ci1hcGkta2V5LWhlcmU=  # your-api-key-here
