fairness_thresholds:
  # Demographic Parity - difference in positive prediction rates
  demographic_parity:
    threshold: 0.1
    description: "Maximum acceptable difference in positive prediction rates between groups"
    
  # Disparate Impact - ratio of positive prediction rates
  disparate_impact:
    threshold: 0.8
    description: "Minimum acceptable ratio of positive prediction rates (protected/unprotected)"
    
  # Equalized Odds - difference in TPR and FPR
  equalized_odds_tpr:
    threshold: 0.1
    description: "Maximum acceptable difference in True Positive Rates between groups"
    
  equalized_odds_fpr:
    threshold: 0.1
    description: "Maximum acceptable difference in False Positive Rates between groups"
    
  # Statistical Parity Difference
  statistical_parity_difference:
    threshold: 0.1
    description: "Maximum acceptable difference in selection rates between groups"
    
  # Individual Fairness
  individual_fairness:
    threshold: 0.05
    description: "Maximum acceptable difference in predictions for similar individuals"

bias_mitigation:
  preprocessing:
    - reweighing
    - disparate_impact_remover
    - lfr  # Learning Fair Representations
    
  inprocessing:
    - adversarial_debiasing
    - fair_classification
    
  postprocessing:
    - calibrated_equalized_odds
    - reject_option_classification

alert_levels:
  critical: 0.2  # Immediate action required
  warning: 0.15  # Monitor closely
  info: 0.1      # Within acceptable range
